fixtures:
  repositories:
    "portmap": "https://github.com/bodgit/puppet-portmap.git"
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"

  symlinks:
    "bootparamd": "#{source_dir}"
